[package]
name = "formula_y"
version = "0.1.0"
edition = "2021"
autotest = false

[lib]
proc-macro = true
path = "src/lib.rs"

[dependencies]
convert_case = "0.5.0"
quote = "1.0.21"
syn = { version = "1.0.99", features = ["extra-traits"] }

